### ISSUE TITLE
docker-compose for PostgreSQL on Centos 7

### ISSUE THREAD

**Issue by rchen8** [CentOS/CentOS-Dockerfiles#149]
I'm trying to perform the same functionality of `docker run -d -p 5432:5432 --name postgresql <yourname>/postgresql && docker exec -it postgresql psql` using `docker-compose`.

This is my `docker-compose.yml` file:
```
version: '3'
services:
  postgresql:
    command: ["/bin/bash", "-c", "psql"]
    image: <yourname>/postgresql:latest
    hostname: postgresql
    build: .
    ports:
      - 5432:5432
```

Yet when I run `docker-compose up` I get the following error message:
```
Creating compose_postgresql_1 ... 
Creating compose_postgresql_1 ... done
Attaching to compose_postgresql_1
postgresql_1  | psql: could not connect to server: No such file or directory
postgresql_1  | 	Is the server running locally and accepting
postgresql_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
compose_postgresql_1 exited with code 2
```

What am I missing?
