### ISSUE TITLE
centos/redis fails to run on OpenShift

### ISSUE THREAD

**Issue by containscafeine** [CentOS/CentOS-Dockerfiles#169]
```console
$ oc logs redis-2-5j58f
7:M 28 Feb 14:12:43.494 # Can't open the append-only file: Permission denied
```
```yaml
- containers:
  - image: centos/redis
    env:
    - name: MASTER
      value: "true"
```
