### ISSUE TITLE
centos/etherpad broken with incompatible versions

### ISSUE THREAD

**Issue by surajssd** [CentOS/CentOS-Dockerfiles#99]
So the centos/etherpad image errors out as 

```
You're running a wrong version of node, or io.js is not installed. You're using v6.7.0, we need v0.10.x, v0.11.x or v0.12.x
```

Recreate issue as

``` yaml
$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER

  etherpad:
    image: centos/etherpad
    ports:
      - "80:9001"
    depends_on:
      - mariadb
    environment:
      DB_HOST: $DB_HOST
      DB_DBID: $DB_NAME
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
```

env file

``` bash
$ cat envs 
DB_HOST=mariadb
ROOT_PASS=etherpad
DB_NAME=etherpad
DB_PASS=etherpad
DB_USER=etherpad
DB_PORT=3306
```

run as

``` bash
$ export $(cat envs )  
$ docker-compose up
Creating network "etherpad_default" with the default driver
Pulling mariadb (centos/mariadb:latest)...
Trying to pull repository docker.io/centos/mariadb ... 
[SNIP]
mariadb_1   | Running mysql_install_db ...
mariadb_1   | Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
etherpad_1  | + '[' '!' -z '' ']'
mariadb_1   | 161019 11:46:38 [Note] /usr/libexec/mysqld (mysqld 5.5.50-MariaDB) starting as process 34 ...
etherpad_1  | + sed -i s/DB_HOST/mariadb/ settings.json
etherpad_1  | + sed -i s/DB_DBID/etherpad/ settings.json
etherpad_1  | + sed -i s/DB_PASS/etherpad/ settings.json
etherpad_1  | + sed -i s/DB_PORT/3306/ settings.json
etherpad_1  | + sed -i s/DB_USER/etherpad/ settings.json
etherpad_1  | + ./bin/run.sh
etherpad_1  | You're running a wrong version of node, or io.js is not installed. You're using v6.7.0, we need v0.10.x, v0.11.x or v0.12.x
mariadb_1   | OK
mariadb_1   | Filling help tables...
[SNIP]
```

See error above `etherpad_1  | You're running a wrong version of node, or io.js is not installed. You're using v6.7.0, we need v0.10.x, v0.11.x or v0.12.x`
